config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  post '/users/:id/update', to: 'users#update'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#create'
  resources :users
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts, only: [:create, :destroy, :show]
  resources :relationships,       only: [:create, :destroy]
  get  '/micropost',  to: 'microposts#show'
  get  '/rank_all',  to: 'microposts#rank_all'
  get '/sort-micropost',  to: 'microposts#index'
  get '/search_micropost',  to: 'microposts#search'
  get '/tag_index',  to: 'microposts#tag_index'
  get '/search_user',  to: 'users#search'
  resources :microposts do
    resources :likes, only: [:create, :destroy]
    resources :comments
  end
  get "users/:id/likes", to: "users#likes"
  get '/microposts/hashtag/:name', to: "microposts#hashtags"
  resources :messages, only: [:create, :destroy]
  resources :rooms, only: [:create, :show, :index]
  
end

app/models/user.rb
#require_dependency '../validators/email_address_validator.rb'

class User < ApplicationRecord
  has_many :microposts, dependent: :destroy
  has_many :likes, dependent: :destroy
  attr_accessor :remember_token
  mount_uploader :image, ImageUploader
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  before_save :email_downcase, unless: :uid?
  validates :name,  presence: true, unless: :uid?, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, unless: :uid?, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    #email_address: true, #複数モデルで使用可能なvalidator作成
                    uniqueness: { case_sensitive: false }
  has_secure_password  validations: false
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  enum user_category: {大学生活前半: 1, 大学生活後半: 2, 就活中: 3, 社会人ルーキー: 4, 社会人ミドル: 5, その他: 6}


  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
  
  def self.search(search)
    if search
      User.where(['name LIKE ?', "%#{search}%"])
    else
      User.all
    end
  end

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def self.find_or_create_from_auth(auth)
    provider = auth[:provider]
    uid = auth[:uid]
    name = auth[:info][:name]
    image = auth[:info][:image]

    self.find_or_create_by(provider: provider, uid: uid) do |user|
      user.name = name
      user.user_category = 'その他'
      if user.image_url?
        user.image_name = image
      else
        user.image_name = "default_user.jpeg"
      end
    end
  end

  private

  def email_downcase
    self.email.downcase!
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :index, :destroy,  :following, :followers]
  before_action :correct_user,   only: [:edit, :update]

  def index
    @q = User.ransack(params[:q])
    @users = @q.result(distinct: true).page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.all.order(created_at: :desc).page(params[:page]).per(20)
    @currentUserEntry=Entry.where(user_id: current_user.id)
    @userEntry=Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      unless @isRoom
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.image_name = "default_user.jpeg"#デフォルトプロフィール
    if @user.save
      log_in(@user)
      flash[:notice] = "Future⇀meへようこそ！"
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:notice] = "プロフィールをアップデートしました"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def following
    @title = "フォローしているユーザー一覧"
    @user  = User.find(params[:id])
    @users = @user.following.page(params[:page]).per(10)
    render 'show_follow'
  end

  def followers
    @title = "フォロワー一覧"
    @user  = User.find(params[:id])
    @users = @user.followers.page(params[:page]).per(10)
    render 'show_follow'
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
        :password_confirmation, :image_name, :user_category, :image)
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, user.id %></div>
  <%= f.submit "フォローする", class: "btn btn-primary w-75 mt-2" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(user) %>
  <div id="follow_form">
  <% if current_user.following?(user) %>
    <%= render partial: 'unfollow', locals: {user: user} %>
  <% else %>
    <%= render partial: 'follow', locals: {user: user} %>
  <% end %>
  </div>
<% end %> 

app/views/users/_form.html.erb
<%= form_for(@user, {multipart: true}) do |f| %>
  <div class="container">
    <div class="row">
      <div class="col-md-3">
      </div>
      <div class="col-md-6 col-md-offset-3">
      <%= render 'shared/error_messages', object: f.object %>
        <div class="card">
          <div class="card-header">
            <h1><%= yield(:button_text) %></h1>
          </div>
          <div class="card-body">
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>

            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control' %>

            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control' %>

            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
            
            <%= f.label :user_category %><br>
            <%= f.radio_button :user_category, :大学生活前半 %>
            <%= f.label :大学生活前半, class: "job_type_label" %>
            <%= f.radio_button :user_category, :大学生活後半 %>
            <%= f.label :大学生活後半, class: "job_type_label" %>
            <%= f.radio_button :user_category, :就活中 %>
            <%= f.label :就活中, class: "job_type_label" %><br>
            <%= f.radio_button :user_category, :社会人ルーキー %>
            <%= f.label :社会人ルーキー, class: "job_type_label" %>
            <%= f.radio_button :user_category, :社会人ミドル %>
            <%= f.label :社会人ミドル, class: "job_type_label" %>
            <%= f.radio_button :user_category, :その他, checked: true %>
            <%= f.label :その他, class: "job_type_label" %>
            <div class="text-right">
      　　     <%= f.submit yield(:button_text), class: "btn btn-success " %>
      　　   </div>
          </div>
        </div>
        <% if current_user%>
          <p>プロフィール画像の更新</p>
          <p><%= f.file_field :image, class: 'form-control' %></p>
        <% end%>
      </div>
    </div>
  </div>
  
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: user.id),
             html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "フォローを解除", class: "btn btn-secondary w-75 mt-2" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "アカウントの更新") %>
<% provide(:button_text, 'アカウントの更新') %>
<div class="users-wrap">

<%= form_for(@user, {multipart: true}) do |f| %>
  <div class="container">
    <div class="row">
      <div class="">
      <%= render 'shared/error_messages', object: f.object %>
        <div class="card">
          <div class="card-header text-center">
            <h2><%= yield(:button_text) %></h2>
          </div>
          <div class="card-body">
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>

            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control' %>

            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control' %>

            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>

            <%= f.label :user_category %><br>
            <%= f.radio_button :user_category, :大学生活前半 %>
            <%= f.label :大学生活前半, class: "job_type_label" %>
            <%= f.radio_button :user_category, :大学生活後半 %>
            <%= f.label :大学生活後半, class: "job_type_label" %>
            <%= f.radio_button :user_category, :就活中 %>
            <%= f.label :就活中, class: "job_type_label" %><br>
            <%= f.radio_button :user_category, :社会人ルーキー %>
            <%= f.label :社会人ルーキー, class: "job_type_label" %>
            <%= f.radio_button :user_category, :社会人ミドル %>
            <%= f.label :社会人ミドル, class: "job_type_label" %>
            <%= f.radio_button :user_category, :その他 %>
            <%= f.label :その他, class: "job_type_label" %>

            <% if current_user%>
              <p>プロフィール画像の更新</p>
              <p><%= f.file_field :image, class: 'form-control' %></p> 
            <% end%>
            <div class="text-right">
      　　     <%= f.submit yield(:button_text), class: "btn btn-success " %>
      　　   </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
  
<% end %>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<div class="users-wrap">
<div class="text-center">
<h2>ユーザー一覧</h2>
</div>
<%= search_form_for @q do |f| %>
  <div class="col-12" style="padding-bottom: 50px;">
  <%= f.label :user_name, "ユーザー"%>
  <%= f.search_field :name_cont, class:"form-control",placeholder: "ユーザー名"  %><br>

  <%= f.label :投稿カテゴリー %><br>
  <%= f.radio_button :user_category_eq, '', checed: true %>指定なし
  <%= f.radio_button :user_category_eq, 1 %>大学生活前半
  <%= f.radio_button :user_category_eq, 2 %>大学生活後半
  <%= f.radio_button :user_category_eq, 3 %>就活中<br>
  <%= f.radio_button :user_category_eq, 4 %>社会人ルーキー
  <%= f.radio_button :user_category_eq, 5 %>社会人ミドル
  <%= f.radio_button :user_category_eq, 6 %>その他

  <div class="float-right">
  <%= f.submit "検索", class: "btn btn-info" %>
  </div>
  </div>
  <div class="btn btn-light">
    <%= sort_link(@q, :created_at, "登録順並びかえ") %>
  </div>
<% end %>
  <% @users.each do |user| %>
    
    <div class="card mb-3" style="max-width: 540px; ">
      <div class="row no-gutters">
        <div class="col-md-3">
        <div class="card-body">
          <% if user.image?%>
          <%= link_to((image_tag user.image.url, :size =>'140x140' , style: "border-radius:10px;" ), user )%>
          <% else %>
          <a href="/users/<%= user.id%>"><img src="<%="/user_images/#{user.image_name}"%>" width="140" height="140", style="border-radius:10px;"></a>
          <% end %>
          </div>
        </div> 
        <div class="col-md-9">
          <div class="card-body", style="margin-left: 30px;">
            <h5 class="card-title"><%= link_to user.name, user %></h5>
            <p class="card-text"><%= render partial: 'shared/user_category_search', locals: { user: user} %></p>
            <!-- 以下DRY化する必要あり -->
            <% user ||= current_user %>
            <div class="stats">
              <a href="<%= following_user_path(user) %>">
                <strong id="following" class="stat">
                  <%= user.following.count %>
                </strong>
                フォロー
              </a>
              <a href="<%= followers_user_path(user) %>">
                <strong id="followers" class="stat">
                  <%= user.followers.count %>
                </strong>
                フォロワー
              </a>
            </div>
　　　　　　　<!-- DRY化する必要あり -->
            <p class="card-text"><small class="text-muted"><%= user.created_at.strftime("%Y-%m-%d ")%>から利用しています。</small></p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <%= paginate @users %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, '新しいアカウントの作成') %>
<div class="form-heading"></div>
  <div class="form users-form">
    <div class="form-body">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/users/search.html.erb
<div class="microposts-wrap">
<p>検索結果</p>
<%= form_tag(search_user_path,:method => 'get') do %>
  <%= text_field_tag :search_user %>
  <%= submit_tag 'Search', :name => nil %>
<% end %>
</div>
<div class="users-wrap">
<h1 class="users-heading">ユーザー検索結果</h1>
  <% @users.each do |user| %>
    <div class="users-index-item">
      <div class="user-left">
        <%#= gravatar_for user, size: 70 %>
        <div class="user-left">
          <img src = "<%="/user_images/#{user.image_name}"%>">
        </div>
      </div>
      <div class="user-right">
        <%= link_to user.name, user %>
        <% user_categorys = {1=>"大学1~2年", 2=>"大学2~3年", 3=>"大学3~4年", 4=>"就活中", 5=>"社会人ルーキー", 6=>"社会人ミドル"} %>
        <%= user_categorys[user.user_category] %>
      </div>
    </div>
  <% end %>
  <%= paginate @users %>
</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="users-wrap">
<div class="row">
  <div class="col-5">
    <% if @user == current_user%>
      <% if @user.image?%>
      <%= link_to((image_tag @user.image.url, :size =>'200', style: "border-radius:10px;"), edit_user_path)%>
      <% else %>
      <a href="/users/<%= @user.id%>/edit"><img src="<%="/user_images/#{@user.image_name}"%>" width="200" height="200", style="border-radius:10px;"></a>
      <% end %>
    <% else %>
      <% if @user.image?%>
      <%= link_to((image_tag @user.image.url, :size =>'200x200', style: "border-radius:10px;"), @user )%>
      <% else %>
      <a href="/users/<%= @user.id%>"><img src="<%="/user_images/#{@user.image_name}"%>" width="200" height="200", style="border-radius:10px;"></a>
      <% end %>
    <% end %>
      </div>
    <div class="col-7">
    <h3><%= @user.name%>(<%= @user.user_category %>)</h3>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
<%= render partial:'follow_form', locals: { user: @user} if logged_in? %>
   <% if @user.id == current_user.id %>

<% else %>
  <% if @isRoom == true %>
    <p><a href="/rooms/<%= @roomId %>" class="btn btn-info w-75 mt-2">チャットルーム</a>
  <% else %>
    <%= form_for @room do |f| %>
      <%= fields_for @entry do |e| %>
        <%= e.hidden_field :user_id, :value=> @user.id %>
      <% end %>
      <%= f.submit "チャットを始める", class: "btn btn-info w-75 mt-2" %>
    <% end %>
  <% end %>
<% end %>

<%= link_to "ユーザー一覧に戻る", users_path, class: "btn btn-success w-75 mt-2" %> 
  </div>
  </div>
</div>

<div class="microposts-wrap">
  <% if @user.microposts.any? %>
    <div class="text-center" style="padding-top: 20px;">
      <h3><%= @user.microposts.count %>件の投稿</h3>
    </div>
    <%= render 'shared/many_microposts2' %>
    <%= paginate @microposts %>
  <% end %>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="users-wrap">
<div class="row">
  <div class="col-5">
      <% if @user.image?%>
      <%= link_to((image_tag @user.image.url, :size =>'200x200', style: "border-radius:10px;"), @user )%>
      <% else %>
      <a href="/users/<%= @user.id%>"><img src="<%="/user_images/#{@user.image_name}"%>" width="200" height="200", style="border-radius:10px;"></a>
      <% end %>
      </div>
    <div class="col-7">
    <h2><%= @user.name%></h2>
<section class="stats">
  <%= render 'shared/stats' %>
</section>
<%= link_to "プロフィールに戻る", @user, class: "btn btn-success w-75 mt-2" %> 
  </div>
  </div>
</div>

<div class="users-wrap">
  <div class="text-center" style="padding-top: 20px;">
    <h3><%= @title %></h3>
  </div>
    <% if @users.any? %>
      <ul class="users follow">
        <% @users.each do |user| %>
    
        <div class="card mb-3" style="max-width: 540px; ">
          <div class="row no-gutters">
            <div class="col-md-3">
              <% if user.image?%>
              <%= link_to((image_tag user.image.url, :size =>'130x140'), user )%>
              <% else %>
              <a href="/users/<%= user.id%>"><img src="<%="/user_images/#{user.image_name}"%>" width="130" height="140"></a>
              <% end %>
            </div> 
            <div class="col-md-9">
              <div class="card-body">
                <h5 class="card-title"><%= link_to user.name, user %></h5>
                <% user_categorys = {1=>"大学1~2年", 2=>"大学2~3年", 3=>"大学3~4年", 4=>"就活中", 5=>"社会人ルーキー", 6=>"社会人ミドル"} %>
                <p class="card-text"><%= user_categorys[user.user_category] %></p>
                <p class="card-text"><small class="text-muted"><%= user.created_at%>から利用しています。</small></p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
      </ul>
      <%= paginate @users %>
    <% end %>
</div>