config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  post '/users/:id/update', to: 'users#update'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#create'
  resources :users
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts, only: [:create, :destroy, :show]
  resources :relationships,       only: [:create, :destroy]
  get  '/micropost',  to: 'microposts#show'
  get  '/rank_all',  to: 'microposts#rank_all'
  get '/sort-micropost',  to: 'microposts#index'
  get '/search_micropost',  to: 'microposts#search'
  get '/tag_index',  to: 'microposts#tag_index'
  get '/search_user',  to: 'users#search'
  resources :microposts do
    resources :likes, only: [:create, :destroy]
    resources :comments
  end
  get "users/:id/likes", to: "users#likes"
  get '/microposts/hashtag/:name', to: "microposts#hashtags"
  resources :messages, only: [:create, :destroy]
  resources :rooms, only: [:create, :show, :index]
  
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-warning" role="alert">
      <%= pluralize(object.errors.count, "") %>つのエラーがあります！
    </div>
    <ul class="alert alert-danger">
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= paginate @feed_items %>
<% end %>

app/views/shared/_many_microposts.erb
<% @microposts.each do |micropost| %>
  <div class="card mb-3" style="max-width: 540px;">
  <div class="card-header">Primaryヘッダ</div>
  <div class="row no-gutters">
  
    <div class="col-md-4">
    <img src = "<%="/user_images/#{micropost.user.image_name}"%>" class="card-img">
    
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">カードのタイトル</h5>
        <p class="card-text">...</p>
        <p class="card-text"><small class="text-muted">最終更新3分前</small></p>
      </div>
    </div>
  </div>
</div>
    <div class="posts-index-item">
      <div class="post-left">
        <img src = "<%="/user_images/#{micropost.user.image_name}"%>">
      </div>
      <div class="post-right">
        <div class="post-user-name">
          <%= link_to(micropost.user.name, "/users/#{micropost.user.id}") %>
          <% micropost_categorys = {1=>"大学1~2年", 2=>"大学2~3年", 3=>"大学3~4年", 4=>"就活中", 5=>"社会人ルーキー", 6=>"社会人ミドル"} %>
          for <%= micropost_categorys[micropost.micropost_category] %>
        </div>
        <%= link_to(micropost.content, "/microposts/#{micropost.id}") %>
      </div>
      <%= image_tag micropost.picture.url if micropost.picture? %>
        <span class="timestamp">

        <div id="likes_buttons_<%= micropost.id %>">
 <%= render partial: 'likes/like', locals: { micropost: micropost, likes: @likes} %>
</div>

        ♥<%= micropost.likes.count%>
          <%= micropost.created_at%>
          <% if current_user?(micropost.user) %>
            <%= link_to "編集", "/microposts/#{micropost.id}/edit" %>
            <%= link_to "削除", micropost, method: :delete,　data: { confirm: "本当に削除しますか?" } %>
          <% end %>
        </span>
    </div>
  <% end %>
  

app/views/shared/_many_microposts2.html.erb
<% @microposts.each do |micropost| %>
  <div class="card mb-3 " style="max-width: 600px;">
    <div class="card-header bg-light text-center">
    <%= render partial: 'shared/user_category_search', locals: { user: micropost.user} %>
      から <%= render partial: 'shared/micropost_category_search', locals: { micropost: micropost} %>への投稿
    </div>
    <div class="row no-gutters">
      <div class="col-md-3">
        <div class="card rounded-0" >
          <div class="row">
          <div class="col-md-12 col-4">
            <div class="text-center" style="margin-top: 14px;">
            <% if micropost.user.image?%>
              <%= link_to((image_tag micropost.user.image.url, :size =>'90', style: "border-radius:10px;"), micropost.user )%>
            <% else %>
            <a href="/users/<%= micropost.user.id%>"><img src="<%="/user_images/#{micropost.user.image_name}"%>" width="90" height="90", style="border-radius:10px;"></a>
            <% end %>
            </div>
          </div>
          <div class="col-md-12 col-6">
            <div class="card-body text-center ">
            <strong><%= link_to(micropost.user.name, "/users/#{micropost.user.id}") %></strong><br>
            <%= render partial: 'shared/user_category_search', locals: { user: micropost.user} %><br>
            <a href="<%= followers_user_path(micropost.user) %>">
                <%= micropost.user.followers.count %>
              フォロワー
            </a>
            </div>
          </div>
          </div>
        </div>
       </div>
      <div class="col-md-9">
        <div class="card-body">
          <div class="">
            <h5 class="card-title">
            <%= raw Rinku.auto_link(render_with_hashtags(micropost.content)) %>
            </h5><br>
            <div class="timestamp text-right">
              <div class="row  justify-content-end">
                <div id="likes_buttons_<%= micropost.id %>">
                <%= render partial: 'likes/like', locals: { micropost: micropost, likes: @likes} %>
                </div>
                <div style="margin-left: 5px;">
                  <a class="post-comment" href="<%="/microposts/#{micropost.id}"%>"><i class="fa fa-comment post-comment"></i><%= micropost.comments.count%></a>
                </div>
                <div>
              　<%= link_to "詳細", "/microposts/#{micropost.id}", class: "btn-sm btn-success", style: "border-radius: 15px;" %>
                <% if current_user?(micropost.user) %>
                <%= link_to "削除", micropost, class: "btn-sm btn-danger", style: "border-radius: 15px;", id: 'delete', method: :delete, data: {confirm: "本当に削除しますか?"} %>
                <% end %>
                </div>
              </div>
            </div>
          </div>
          <p class="card-text text-right"><small class="text-muted"><%= micropost.created_at.strftime("%Y-%m-%d %H:%M")%>に投稿しました </small></p>
        </div>
        
      </div>
    </div>
    <% if micropost.picture? %>
    <div class="card-footer text-center">
    <%= image_tag micropost.picture.url if micropost.picture? %>
    </div>
    <% end %>
  </div>
<% end %>

app/views/shared/_micropost_category_search.html.erb
<% micropost_category_hash = {'大学生活前半' => 1, '大学生活後半' => 2, '就活中' => 3, '社会人ルーキー' => 4, '社会人ミドル' => 5, 'その他' => 6}%>
<% micropost_category_number = micropost_category_hash[micropost.micropost_category]%>
<%= link_to micropost.micropost_category, sort_micropost_path(q: {micropost_category_eq: micropost_category_number }), class: category_button_color(micropost.micropost_category), style: "border-radius: 10px;"%>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost_form, {multipart: true}) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="form-controll">
    <%= f.text_area :content, class: "form-controll col-12 ",style: "border-radius:10px; border-color:#acabab; border-width: 3px; ", id: 'content', rows: "4", placeholder: "過去の自分にアドバイスをつぶやこう！...                       #ハッシュタグ　リンク（http//...）" %>
  </div>
  <div class="text-center" style="color: rgb(120, 120, 120);" >
  <h5>投稿したい相手のカテゴリー</h5>  
    <%= f.radio_button :micropost_category, :大学生活前半 %>
    <%= f.label :大学生活前半, class: "job_type_label" %>
    <%= f.radio_button :micropost_category, :大学生活後半 %>
    <%= f.label :大学生活後半, class: "job_type_label" %>
    <%= f.radio_button :micropost_category, :就活中 %>
    <%= f.label :就活中, class: "job_type_label" %><br>
    <%= f.radio_button :micropost_category, :社会人ルーキー %>
    <%= f.label :社会人ルーキー, class: "job_type_label" %>
    <%= f.radio_button :micropost_category, :社会人ミドル %>
    <%= f.label :社会人ミドル, class: "job_type_label" %>
    <%= f.radio_button :micropost_category, :その他, checked: true %>
    <%= f.label :その他, class: "job_type_label" %>
  </div>
    <%= f.file_field :picture, class: "btn btn-light float-right w-100 mt-2 ", accept: 'image/jpeg,image/gif,image/png' %>
    <%= f.submit "投稿", class: "btn btn-info float-right w-100 mt-2 " %>
    </span>
<% end %>


<script type="text/javascript">
  $('#micropost_picture').bind('change', function() { 
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('ファイルのサイズが5MBを超えています。サイズを小さくしてしてください。');
    }
  });
</script>

app/views/shared/_micropost_show.html.erb
<div class="card mb-3" style="max-width: 600px;">
    <div class="card-header text-center">
      <%= render partial: 'shared/user_category_search', locals: { user: @micropost.user} %>
      から <%= render partial: 'shared/micropost_category_search', locals: { micropost: @micropost} %>への投稿
    </div> 
    <div class="row no-gutters">
      <div class="col-md-3">
        <div class="card rounded-0" >
          <div class="row">
          <div class="col-md-12 col-4">
            <div class="text-center" style="margin-top: 14px;">
            <% if @micropost.user.image?%>
              <%= link_to((image_tag @micropost.user.image.url, :size =>'90', style: "border-radius:10px;"), @micropost.user )%>
            <% else %>
            <a href="/users/<%= @micropost.user.id%>"><img src="<%="/user_images/#{@micropost.user.image_name}"%>" width="90" height="90", style="border-radius:10px;"></a>
            <% end %>
            </div>
          </div>
          <div class="col-md-12 col-6">
            <div class="card-body text-center ">
            <strong><%= link_to(@micropost.user.name, "/users/#{@micropost.user.id}") %></strong><br>
            <%= render partial: 'shared/user_category_search', locals: { user: @micropost.user} %><br>
            <a href="<%= followers_user_path(@micropost.user) %>">
                <%= @micropost.user.followers.count %>
              フォロワー
            </a>
            </div>
          </div>
          </div>
        </div>
       </div>
      <div class="col-md-9">
        <div class="card-body">
          <div class="">
            <h5 class="card-title">
            <%= raw Rinku.auto_link(render_with_hashtags(@micropost.content)) %>
            </h5><br>
            <div class="timestamp text-right">
              <div class="row  justify-content-end">
                <div id="likes_buttons_<%= @micropost.id %>">
                <%= render partial: 'likes/like', locals: { micropost: @micropost, likes: @likes} %>
                </div>
                <div>
                <% if current_user?(@micropost.user) %>
                <%= link_to "削除", @micropost, class: "btn-sm btn-danger", style: "border-radius: 15px;", id: 'delete', method: :delete, data: {confirm: "本当に削除しますか?"} %>
                <% end %>
                </div>
              </div>
            </div>
          </div>
          <p class="card-text text-right"><small class="text-muted"><%= @micropost.created_at.strftime("%Y-%m-%d %H:%M")%> </small></p>
        </div>
        
      </div>
    </div>
    <% if @micropost.picture? %>
    <div class="card-footer text-center">
    <%= image_tag @micropost.picture.url if @micropost.picture? %>
    </div>
    <% end %>
  </div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    フォロー
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    フォロワー
  </a>
</div>

app/views/shared/_user_category_search.html.erb
<% user_category_hash = {'大学生活前半' => 1, '大学生活後半' => 2, '就活中' => 3, '社会人ルーキー' => 4, '社会人ミドル' => 5, 'その他' => 6}%>
<% user_category_number = user_category_hash[user.user_category]%>
<%= link_to user.user_category, users_path(q: {user_category_eq: user_category_number }), class: category_button_color(user.user_category), style: "border-radius: 10px;" %>

app/views/shared/_user_info.html.erb
<div class="">
<% if @user.image?%>
<%= link_to((image_tag @user.image.url, size: "135", style: "border-radius:10px;"), @user )%>
<% else %>
<a href="/users/<%= @user.id%>"><img src="<%="/user_images/#{@user.image_name}"%>" width="135" height="135", style="border-radius:10px;"></a>
<% end %>
<p><%=link_to current_user.name, current_user, class: "text-center" %></p>

<strong><%= link_to "プロフィール", current_user, class: "mx-auto"%></strong><br>
<%= pluralize(current_user.microposts.count, "件の投稿") %>
</div>
<section class="stats">
  <%= render 'shared/stats' %>
</section>