config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  post '/users/:id/update', to: 'users#update'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#create'
  resources :users
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts, only: [:create, :destroy, :show]
  resources :relationships,       only: [:create, :destroy]
  get  '/micropost',  to: 'microposts#show'
  get  '/rank_all',  to: 'microposts#rank_all'
  get '/sort-micropost',  to: 'microposts#index'
  get '/search_micropost',  to: 'microposts#search'
  get '/tag_index',  to: 'microposts#tag_index'
  get '/search_user',  to: 'users#search'
  resources :microposts do
    resources :likes, only: [:create, :destroy]
    resources :comments
  end
  get "users/:id/likes", to: "users#likes"
  get '/microposts/hashtag/:name', to: "microposts#hashtags"
  resources :messages, only: [:create, :destroy]
  resources :rooms, only: [:create, :show, :index]
  
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :logged_in_user

  def create
    @room = Room.create
    @entry1 = Entry.create(room_id: @room.id, user_id: current_user.id)
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(room_id: @room.id))
    redirect_to room_path @room.id
  end

  def show
    @room = Room.find(params[:id])
    if Entry.where(user_id: current_user.id, room_id: @room.id).present?
      @messages = @room.messages
      @message = Message.new
      @entries = @room.entries
    else
      redirect_back(fallback_location: root_path)
    end
  end
end
  

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/show.html.erb
<h1>チャットルーム</h1>
<div class="col-8">
<h4>参加者 =>
<% @entries.each do |e| %>
  <a href="/users/<%= e.user.id %>"><%= e.user.name%>さん</a>
<% end %></h4>


<% if @messages.present? %>

  <% @messages.each do |m| %>
  <div class="card">
  <div class="card-body">
  <div class="row">
  <div class="col-3">
  <% if m.user.image?%>
  <%= link_to((image_tag m.user.image.url, :size =>'50x50', style: "border-radius:10px;"), m.user )%>
  <% else %>
  <a href="/users/<%= m.user.id%>"><img src="<%="/user_images/#{m.user.image_name}"%>" width="50" height="50", style="border-radius:10px;"></a>
  <% end %><br>
  <small><a href="/users/<%= m.user_id %>"><%= m.user.name %></a>さん</small>
  </div>
  <div class="col-9">
   <strong><%= m.content %></strong><br>
   <small class="text-muted text-right"><%= m.created_at.strftime("%Y-%m-%d %H:%M")%>にコメントしました。 </small>
   <% if m.user == current_user %>
   <%= link_to '削除', message_path(m.id), class: "btn btn-danger float-right", method: :delete, data: {confirm: "本当に削除しますか?"}, remote: true %>
   <% end %>
  </div>
  </div>
  </div>
  </div> 

  <% end %>
 
<% else %>
  <h3 class="text-center" style="padding: 100px 0px;">メッセージはまだありません</h3>
<% end %>



<%= form_for @message do |f| %>
  
  <%= f.text_field :content, placeholder: "メッセージを入力して下さい" , class: "form-control", style: "margin-top: 30px;  border-color:#acabab;" %>
  <%= f.hidden_field :room_id, :value => @room.id %>
  <tr>
  <%= f.submit "投稿する", class: "btn btn-info float-right w-50 mt-2" %>
  </tr>
<% end %>
<tr>
<%= link_to "ユーザー一覧に戻る", users_path, class: "btn btn-success float-right w-50 mt-2"%>
</tr>
</div>