config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  post '/users/:id/update', to: 'users#update'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#create'
  resources :users
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts, only: [:create, :destroy, :show]
  resources :relationships,       only: [:create, :destroy]
  get  '/micropost',  to: 'microposts#show'
  get  '/rank_all',  to: 'microposts#rank_all'
  get '/sort-micropost',  to: 'microposts#index'
  get '/search_micropost',  to: 'microposts#search'
  get '/tag_index',  to: 'microposts#tag_index'
  get '/search_user',  to: 'users#search'
  resources :microposts do
    resources :likes, only: [:create, :destroy]
    resources :comments
  end
  get "users/:id/likes", to: "users#likes"
  get '/microposts/hashtag/:name', to: "microposts#hashtags"
  resources :messages, only: [:create, :destroy]
  resources :rooms, only: [:create, :show, :index]
  
end

app/views/layouts/_header1.html.erb
<header>
<nav class="navbar navbar-expand-lg navbar-dark bg-selected fixed-top" style="border-radius:25px;">
  <div class="navbar-brand">
    <%= link_to "future⇀me", root_path, class: "logo1" %>
  </div>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse " id="navbarSupportedContent">
  <ul class="navbar-nav mr-auto">
  <% if logged_in? %>
    <li class="nav-item active dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fa fa-book "></i> メニュー
      </a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
      <a class="dropdown-item" href="users"><i class="fas fa-users"></i>ユーザー一覧</a>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="/rank_all"><i class="fas fa-bar-chart-o"></i>全体ランキング</a>
        <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="/sort-micropost"><i class="fas fa-search"></i>投稿詳細検索</a>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="/tag_index"><i class="fas fa-tags"></i>ハッシュタグ一覧</a>
      </div>
    </li>
    <li class="nav-item active dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
       <i class="fa fa-gear"></i>設定
      </a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
      <%= link_to "プロフィール編集", edit_user_path(current_user), class: "dropdown-item" %>
        <div class="dropdown-divider"></div>
        <%= link_to "ログアウト", logout_path, method: :delete, class: "dropdown-item" %>
      </div>
    </li>
    <li class="nav-item active">
      <a class="nav-link" href="/"><i class="fas fa-send"></i> 投稿する<span class="sr-only">(current)</span></a>
    </li>
  <% else %>
    <li class="nav-item active">
      <%= link_to "新規登録", signup_path, class: "nav-link" %><span class="sr-only">(current)</span>
    </li>
    <li class="nav-item active">
      <%= link_to "ログイン", login_path, class: "nav-link" %><span class="sr-only">(current)</span>
    </li>
    <li class="nav-item active">
    <%= form_for(:session, url: login_path) do |f| %>
      <%= f.hidden_field :email, {value: 'test@testuser1.com'} %>
      <%= f.hidden_field :password, {value: 'password'} %>
      <%= f.submit "簡単ログイン!!", class: "btn btn-warning", style: "color: white; border-radius: 20px;" %>
    <% end %>
    </li>
    
  <% end %>  
  </ul>
  <% if logged_in? %>
  <form action="/search_micropost" accept-charset="UTF-8" method="get" class="form-inline my-2 my-lg-0">
    <input class="form-control mr-sm-2" style="border-radius:20px;" type="text" placeholder="投稿内容、ユーザー名" aria-label="Search" name="q">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit" style="border-radius:20px;">検索</button>
  </form>
  <% end%> 
</div>
</nav>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_sidebar-right.html.erb
<div class='mx-auto sticky-top' style="width: 250px;">
<div class="row sidebar-right">
  <div class="card" style="width: 18rem;">
    <div class="card-body sidebar-right-color">
      <h5 class="card-title">#ハッシュタグ</h5>
      <h6 class="card-subtitle mb-2 text-muted">キーワード</h6>
      <% @side_tags.each do |tag|%>
      <%= link_to(tag_back_to_hash(tag.name), "/microposts/hashtag/#{tag.name}", style: "font-size: #{tag_size(tag.microposts.count)}px;") %>
      <% end %>
    </div>
  </div>
  <div class="card" style="width: 18rem;">
    <div class="card-body sidebar-right-color">
      <h5 class="card-title　">話題の投稿</h5>
      <h6 class="card-subtitle mb-2 text-muted">直近1ヶ月で、<br>いいねが多かった投稿</h6>
      <h6 class="card-subtitle mb-2 text-muted"></h6>
      <% @recent_microposts.each do |micropost|%>
        <%= link_to(micropost.content, "/microposts/#{micropost.id}") %><br>
        <% end %>
    </div>
  </div>
<div>
<div>

app/views/layouts/_sidebar.html.erb
<div class="wrapper-s">
<div class="sidebar" >
 <h2>Sidebar</h2>
<ul>
　<li><a href="/"><i class="fas fa-home"></i>ホーム</a></li>
  <li><a href="/users/<%= current_user.id%>"><i class="fas fa-user"></i>プロフィール</a></li>
  <li><a href="/users"><i class="fas fa-users"></i>ユーザー一覧・検索</a></li>
  <li><a href="/rank_all"><i class="fas fa-bar-chart-o"></i>全体ランキング</a></li>
  <li><a href="/sort-micropost"><i class="fas fa-search"></i>投稿一覧・検索</a></li>
  <li><a href="/tag_index"><i class="fas fa-tags"></i>ハッシュタグ一覧</a></li>
</ul> 
<div class="social_media">
<a href="https://www.facebook.com/sharer/sharer.php?u=https://future-me7.com&text=future-me~未来の自分からアドバイスを受け取ろう！" title='Facebook' target='_blank' ><i class="fab fa-facebook-f"></i></a>
<a href="https://twitter.com/share?url=https://future-me7.com&text=future-me~未来の自分からアドバイスを受け取ろう！" title='Twitter' target='_blank' ><i class="fab fa-twitter"></i></a>
</div>
</div>
</div>                         

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>


    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= render 'layouts/shim'%>
    <script src="https://kit.fontawesome.com/b99e675b6e.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
    <%= render 'layouts/header1'%>
      <% if logged_in? %>
      <div class="row no-gutters">
        <div class="col-md-3 d-none d-md-block ">
          <%= render 'layouts/sidebar'%>
        </div>
          <div class="col-md-6">
       　   <div class="home-wrap"> 
              <% if flash[:notice] %>
                <div class="alert alert-primary alert-dismissible fade show">
                  <%= flash[:notice] %>
                  <button type="button" class="close" data-dismiss="alert" aria-label="閉じる">
                  <span aria-hidden="true">&times;</span>
      　          </button>
                </div> 
              <% end %>
              <% if flash[:danger] %>
                <div class="alert alert-danger alert-dismissible fade show">
                  <%= flash[:danger] %>
                  <button type="button" class="close" data-dismiss="alert" aria-label="閉じる">
                  <span aria-hidden="true">&times;</span>
      　          </button>
                </div> 
              <% end %>
              <%= yield %>
　　　　　    </div>
            
          </div>
          <div class="col-md-3 d-md-block ">
            <%= render 'layouts/sidebar-right'%>
          </div>
        </div>
      <% else %>
        <%= yield %>
      <% end %>
  </body>
  
</html>